version: "3"
services:
    discord-bot:
        image: ducksel/discord-team-generator-bot:latest
        volumes:
          - ./matches:/matches:rw
        env_file:
          - .env
        command: ["java", "-jar", "-DBotToken=$DISCORD_BOT_TOKEN", "-DMembersPerPage=$MEMBERS_PER_PAGE", "/app.jar"]