version: "3"
services:
    discord-bot:
        image: ducksel/discord-team-generator-bot:latest
        volumes:
          - ./matches:/matches:rw
        environment:
          DISCORD_BOT_TOKEN: "<your-bot-token>"
        command: ["java", "-jar", "-DBotToken=$DISCORD_BOT_TOKEN", "/app.jar"]